-- Steps para SOP 2
DELETE FROM knowledge_sop_steps WHERE sop_id = (SELECT id FROM knowledge_sops WHERE slug = 'tbo-3d-015-fluxo-d3d-pipeline-producao');
INSERT INTO knowledge_sop_steps (sop_id, title, content, step_type, order_index)
SELECT id, 'Objetivo', E'Definir o fluxo completo de gestão de produção da BU Digital 3D — do briefing à entrega final — usando o TBO OS como sistema de controle, garantindo previsibilidade de prazo, qualidade consistente e visibilidade de status para todas as partes envolvidas em cada projeto.', 'step', 0
FROM knowledge_sops WHERE slug = 'tbo-3d-015-fluxo-d3d-pipeline-producao'
UNION ALL
SELECT id, 'Escopo', E'Aplica-se a todos os projetos de Digital 3D: renders estáticos, animações, tours 360°, implantações e plantas humanizadas/perspectivadas. Gerido pelo Líder de D3D com suporte de Operações. Inicia no kick-off do projeto e termina com o aceite formal do cliente e arquivamento de assets.', 'step', 1
FROM knowledge_sops WHERE slug = 'tbo-3d-015-fluxo-d3d-pipeline-producao'
UNION ALL
SELECT id, 'RACI', E'| Etapa | Responsável | Aprovador | Consultado | Informado |\n|-------|-------------|-----------|------------|-----------|\n| Briefing e kick-off | Atendimento + Líder D3D | Dir. Criativo | Cliente | Operações |\n| Planejamento e cronograma | Líder D3D | Operações | Time D3D | Comercial |\n| Modelagem 3D | Modelador | Líder D3D | — | — |\n| Iluminação e materiais | 3D Artist | Líder D3D | Dir. Criativo | — |\n| Render e pós-produção | 3D Artist | Líder D3D | — | — |\n| QA interno | Líder D3D | Dir. Criativo | — | Atendimento |\n| Apresentação ao cliente | Atendimento | Líder D3D | Comercial | — |\n| Revisões | 3D Artist | Líder D3D | Cliente | Atendimento |\n| Entrega final | Atendimento | Líder D3D | — | Comercial |', 'step', 2
FROM knowledge_sops WHERE slug = 'tbo-3d-015-fluxo-d3d-pipeline-producao'
UNION ALL
SELECT id, 'Pré-requisitos', E'- Contrato assinado e adiantamento recebido (quando aplicável pelo contrato)\n- Briefing criativo completo: plantas (DWG/PDF), referências visuais, paleta de cores, lista de peças definida\n- Acesso a todos os arquivos do projeto no Google Drive do cliente\n- Projeto criado no TBO OS — Módulo D3D Pipeline — com cronograma\n- Líder D3D confirmou viabilidade técnica e disponibilidade do time', 'step', 3
FROM knowledge_sops WHERE slug = 'tbo-3d-015-fluxo-d3d-pipeline-producao'
UNION ALL
SELECT id, 'Procedimento', E'**Etapa 1 — Kick-off e Planejamento (Dias 1–2)**\n1. Reunião de kick-off: Atendimento + Líder D3D + cliente\n2. Validar lista de peças, formatos, câmeras e resoluções\n3. Preencher template de escopo técnico D3D\n4. Criar projeto no TBO OS com tarefas, responsáveis e prazos\n5. Definir milestone de QA interno (D-2 antes da entrega)\n\n**Etapa 2 — Modelagem**\n1. 3D Artist recebe tarefa no TBO OS com briefing técnico\n2. Modela seguindo plants, com naming convention por layer\n3. Checkpoint com Líder D3D ao final da modelagem antes de avançar\n\n**Etapa 3 — Iluminação, Materiais e Render**\n1. Aplicar materiais conforme referências do briefing\n2. Configurar iluminação (natural/artificial/exterior/interior)\n3. Render parcial de teste → aprovação → render final\n\n**Etapa 4 — Pós-produção**\n1. Pós em Photoshop/Lightroom conforme SOP tbo-3d-004\n2. Salvar PSD + exportar JPEG/PNG na resolução correta\n\n**Etapa 5 — QA Interno (D-2 obrigatório)**\n1. Líder D3D revisa todas as peças com checklist tbo-3d-012\n2. Corrige issues antes de enviar ao cliente\n\n**Etapa 6 — Apresentação e Revisões**\n1. Atendimento envia galeria ao cliente com 5 dias de prazo\n2. Consolida feedbacks, classifica in/out de escopo\n3. Máx. 2 rodadas de revisão por contrato padrão\n\n**Etapa 7 — Entrega Final**\n1. QA final, exportar pacote organizado por tipo de peça\n2. Upload na pasta do cliente, aceite formal, NPS\n3. Fechar projeto no TBO OS e atualizar biblioteca de assets', 'step', 4
FROM knowledge_sops WHERE slug = 'tbo-3d-015-fluxo-d3d-pipeline-producao'
UNION ALL
SELECT id, 'Checklist de Validação', E'- [ ] Lista de peças validada com cliente antes de iniciar\n- [ ] Cronograma no TBO OS com milestones claros\n- [ ] Checkpoint de modelagem aprovado antes do render\n- [ ] QA interno realizado com D-2 de antecedência\n- [ ] Máximo 2 rodadas de revisão aplicadas\n- [ ] Resolução e formato corretos para cada uso final\n- [ ] Assets arquivados na biblioteca D3D\n- [ ] Projeto fechado no TBO OS com NPS coletado', 'checkpoint', 5
FROM knowledge_sops WHERE slug = 'tbo-3d-015-fluxo-d3d-pipeline-producao'
UNION ALL
SELECT id, 'Ferramentas e Recursos', E'- **3D**: 3ds Max, SketchUp, Rhino (conforme especialidade)\n- **Render**: V-Ray, Corona Renderer, Chaos Cloud (farm)\n- **Pós-produção**: Adobe Photoshop, Lightroom\n- **Gestão de produção**: TBO OS — Módulo D3D Pipeline\n- **Compartilhamento**: Google Drive (estrutura padrão por cliente)\n- **Referências**: Biblioteca de materiais TBO (texturas, mobiliário, vegetação)\n- **QA**: Checklist SOP tbo-3d-012', 'tip', 6
FROM knowledge_sops WHERE slug = 'tbo-3d-015-fluxo-d3d-pipeline-producao'
UNION ALL
SELECT id, 'SLAs e Métricas', E'| Tipo de Peça | SLA Interno | SLA Cliente |\n|-------------|-------------|-------------|\n| Render estático simples | 3 dias úteis | 5 dias úteis |\n| Render estático complexo | 5 dias úteis | 7 dias úteis |\n| Planta humanizada | 2 dias úteis | 3 dias úteis |\n| Tour 360° | 7 dias úteis | 10 dias úteis |\n| Animação até 60s | 10 dias úteis | 15 dias úteis |\n\n**KPIs do Pipeline D3D:**\n- Prazo cumprido: ≥90% dos projetos\n- QA interno: 100% das peças revisadas antes de envio\n- Revisões dentro do escopo: ≤2 rodadas em 85% dos projetos\n- NPS médio: ≥8.5', 'note', 7
FROM knowledge_sops WHERE slug = 'tbo-3d-015-fluxo-d3d-pipeline-producao'
UNION ALL
SELECT id, 'Troubleshooting', E'**Plantas incompletas ou com erros**\n→ Não iniciar modelagem. Solicitar ao Atendimento esclarecimento com o cliente. Registrar bloqueio no TBO OS.\n\n**Render com artefatos ou ruído excessivo**\n→ Aumentar samples. Verificar configurações de GI. Nunca entregar render abaixo do padrão TBO.\n\n**Prazo em risco por volume de peças**\n→ Escalar para Líder D3D em D-3. Avaliar farm de render, terceirização ou negociação de prazo.\n\n**Cliente solicita mudança de escopo**\n→ Paralisar, emitir aditivo comercial. Retomar apenas após aprovação formal.\n\n**Arquivos do cliente incompatíveis**\n→ Solicitar novo arquivo ou cobrar hora de retrabalho técnico.', 'warning', 8
FROM knowledge_sops WHERE slug = 'tbo-3d-015-fluxo-d3d-pipeline-producao'
UNION ALL
SELECT id, 'Template Anexo — Escopo Técnico D3D', E'```markdown\n# Escopo Técnico D3D — [CLIENTE] / [EMPREENDIMENTO]\nData: _______ | Líder D3D: _______ | Prazo de entrega: _______\n\n## Lista de Peças\n| # | Tipo | Câmera/Descrição | Resolução | Formato | Prazo Interno |\n|---|------|-----------------|-----------|---------|---------------|\n| 1 | Render Ext. | Fachada Principal | 5000x3000px | JPEG | _______ |\n| 2 | Render Int. | Living Room | 4000x3000px | JPEG | _______ |\n| 3 | Planta Human. | Tipo A - 3 dorms | A3 300dpi | PNG | _______ |\n\n## Referências\n- Moodboard: [LINK]\n- Paleta de cores: [LINK]\n- Estilo de iluminação: _______ | Público-alvo: _______\n\n## Observações Técnicas\n- Software: _______ | Render engine: _______\n- Farm de render: Sim / Não | Estimativa: ___h\n- Elementos especiais: _______\n\n## Aprovações\n- Líder D3D: _________________ Data: _______\n- Atendimento: _________________ Data: _______\n```', 'tip', 9
FROM knowledge_sops WHERE slug = 'tbo-3d-015-fluxo-d3d-pipeline-producao';