-- Steps para SOP 1
DELETE FROM knowledge_sop_steps WHERE sop_id = (SELECT id FROM knowledge_sops WHERE slug = 'tbo-av-009-pos-producao-edicao-color-finalizacao');
INSERT INTO knowledge_sop_steps (sop_id, title, content, step_type, order_index)
SELECT id, 'Objetivo', E'Padronizar o fluxo completo de pós-produção audiovisual da TBO — da ingestão do material bruto à entrega final aprovada — garantindo qualidade cinematográfica, consistência de cor, sincronização de áudio e cumprimento de prazos em todos os projetos de filme, teaser, institucional e conteúdo para redes sociais.', 'step', 0
FROM knowledge_sops WHERE slug = 'tbo-av-009-pos-producao-edicao-color-finalizacao'
UNION ALL
SELECT id, 'Escopo', E'Aplica-se a todos os projetos audiovisuais: filmes de lançamento, teasers, vídeos institucionais, pílulas de redes sociais e vídeos de produto. Executado pela equipe de AV após o dia de filmagem. Inicia após a transferência e backup do material captado e termina com o upload dos arquivos finais e fechamento do projeto no TBO OS.', 'step', 1
FROM knowledge_sops WHERE slug = 'tbo-av-009-pos-producao-edicao-color-finalizacao'
UNION ALL
SELECT id, 'RACI', E'| Atividade | Responsável | Aprovador | Consultado | Informado |\n|-----------|-------------|-----------|------------|-----------|\n| Ingestão e backup | Editor | Líder AV | — | Diretor Criativo |\n| Montagem offline | Editor | Líder AV | Diretor AV | — |\n| Revisão de corte | Líder AV | Diretor Criativo | Cliente | Atendimento |\n| Color grading | Colorista | Diretor AV | Editor | — |\n| Mix de áudio | Editor | Líder AV | — | — |\n| Entrega rascunho | Atendimento | Líder AV | — | Comercial |\n| Revisões do cliente | Editor | Líder AV | — | — |\n| Master e exports | Editor | Líder AV | — | Atendimento |', 'step', 2
FROM knowledge_sops WHERE slug = 'tbo-av-009-pos-producao-edicao-color-finalizacao'
UNION ALL
SELECT id, 'Pré-requisitos', E'Antes de iniciar a pós-produção, verificar:\n\n- Material bruto transferido e com backup em pelo menos 2 locais (HD local + nuvem)\n- Briefing criativo do projeto disponível e acessível no TBO OS\n- Roteiro/storyboard aprovado disponível para referência de montagem\n- Trilha sonora aprovada ou em negociação de licença (nunca usar sem licença)\n- Acesso ao projeto no TBO OS com checklist de entrega atualizado\n- Workstation de edição com espaço mínimo de 500GB disponível para o projeto', 'step', 3
FROM knowledge_sops WHERE slug = 'tbo-av-009-pos-producao-edicao-color-finalizacao'
UNION ALL
SELECT id, 'Procedimento', E'**Fase 1 — Ingestão e Organização (Dia 1)**\n1. Transferir arquivos para estrutura de pastas padronizada: RAW/CAM_A, RAW/CAM_B, RAW/DRONE, AUDIO, REFERENCIAS, EXPORTS\n2. Confirmar integridade dos arquivos (checksum MD5)\n3. Backup imediato na nuvem (Google Drive Shared Drive)\n4. Criar projeto no software de edição e sincronizar áudio com vídeo\n\n**Fase 2 — Montagem Offline (Dias 2–4)**\n1. Assistir todo material e marcar takes favoritos\n2. Montar primeiro rascunho seguindo roteiro/storyboard\n3. Revisão interna (Líder AV + Diretor Criativo) em reunião de 45 min\n4. Incorporar feedback e fechar corte para aprovação do cliente\n\n**Fase 3 — Aprovação do Cliente (Dias 5–6)**\n1. Exportar link privado (Vimeo/Frame.io) com prazo de feedback de 48h\n2. Incorporar feedback via Atendimento (máx. 2 rodadas)\n3. Emitir aditivo se alterações excederem escopo contratual\n\n**Fase 4 — Color Grading (Dias 7–8)**\n1. Balancear exposição e balanço de branco\n2. Aplicar look criativo alinhado ao briefing\n3. Garantir consistência entre câmeras e cenas\n4. Revisar em monitor calibrado (Rec.709)\n\n**Fase 5 — Mix de Áudio (Dias 8–9)**\n1. Limpar ruídos de fundo (iZotope RX)\n2. Normalizar loudness: -14 LUFS para web, -23 LUFS para broadcast\n3. Mixar versão com e sem narração quando aplicável\n\n**Fase 6 — Exports Finais (Dia 10)**\n1. Renderizar master ProRes 4444 para arquivo\n2. Exportar: H.264 1080p, 4K, 9:16 vertical, 1:1 feed\n3. Nomear: [CLIENTE]_[EMPREEND]_[TIPO]_[RES]_v[N]_[DATA].mp4\n4. Upload para pasta de entrega + enviar link ao Atendimento', 'step', 4
FROM knowledge_sops WHERE slug = 'tbo-av-009-pos-producao-edicao-color-finalizacao'
UNION ALL
SELECT id, 'Checklist de Validação', E'- [ ] Material bruto com backup em 2 locais confirmado\n- [ ] Sync de áudio verificado em todas as cenas\n- [ ] Corte aprovado pelo Diretor Criativo antes do color grading\n- [ ] Máximo 2 rodadas de revisão do cliente incorporadas\n- [ ] Color grading revisado em monitor calibrado\n- [ ] Loudness dentro do padrão da plataforma de destino\n- [ ] Todas as versões de formato exportadas (1:1, 16:9, 9:16)\n- [ ] Master ProRes arquivado com backup confirmado\n- [ ] Arquivos nomeados seguindo convenção TBO\n- [ ] Link de entrega enviado ao Atendimento\n- [ ] Projeto fechado no TBO OS', 'checkpoint', 5
FROM knowledge_sops WHERE slug = 'tbo-av-009-pos-producao-edicao-color-finalizacao'
UNION ALL
SELECT id, 'Ferramentas e Recursos', E'- **Edição não-linear**: Adobe Premiere Pro ou DaVinci Resolve 19\n- **Color grading**: DaVinci Resolve (página Colour)\n- **Limpeza de áudio**: Adobe Audition + iZotope RX 10\n- **Review com cliente**: Frame.io (preferência) ou Vimeo Review\n- **Armazenamento**: Google Drive Shared Drive + HD externo (mín. 2TB por projeto grande)\n- **Calibração de cor**: Monitor com perfil Rec.709 + ColorChecker Passport\n- **Conversão de formatos**: HandBrake (gratuito)\n- **Sincronização de áudio**: PluralEyes (Premiere) ou AutoSync (DaVinci)', 'tip', 6
FROM knowledge_sops WHERE slug = 'tbo-av-009-pos-producao-edicao-color-finalizacao'
UNION ALL
SELECT id, 'SLAs e Métricas', E'| Etapa | SLA | KPI de Qualidade |\n|-------|-----|------------------|\n| Ingestão e organização | 1 dia útil | 100% material com backup verificado |\n| Montagem offline | 3 dias úteis | Aprovação interna em máx. 1 review |\n| Rascunho ao cliente | 2 dias úteis para feedback | Máx. 2 rodadas de revisão |\n| Color grading | 2 dias úteis | Aprovação Diretor Criativo em 1 review |\n| Mix de áudio | 1 dia útil | Loudness dentro do padrão |\n| Exports e entrega | 1 dia útil | 100% formatos entregues sem retrabalho |\n| **Total projeto** | **10 dias úteis** | Prazo cumprido ≥95% dos projetos |', 'note', 7
FROM knowledge_sops WHERE slug = 'tbo-av-009-pos-producao-edicao-color-finalizacao'
UNION ALL
SELECT id, 'Troubleshooting', E'**Material corrompido ou arquivo faltando**\n→ Verificar backup secundário imediatamente. Se irrecuperável, comunicar Líder AV e Atendimento para alinhar reshoot ou alternativa criativa com cliente.\n\n**Sync de áudio impossível (sem claquete ou referência)**\n→ Usar picos de som intensos como referência manual. PluralEyes automatiza em ~90% dos casos.\n\n**Cliente solicita 3ª rodada de revisão (além do escopo)**\n→ Paralisar, emitir aditivo via Atendimento. Retomar apenas após aprovação formal e pagamento quando aplicável.\n\n**Prazo em risco (D-3 antes da entrega)**\n→ Escalar para Líder AV. Opções: paralelizar color e audio, terceirizar colorização, alocar editor adicional.\n\n**Incompatibilidade de codecs na ingestão**\n→ Usar HandBrake para conversão antes de importar no NLE. Documentar câmeras problemáticas para futuras produções.', 'warning', 8
FROM knowledge_sops WHERE slug = 'tbo-av-009-pos-producao-edicao-color-finalizacao'
UNION ALL
SELECT id, 'Template Anexo — Checklist de Entrega AV', E'```markdown\n# Checklist de Entrega — [PROJETO] — [DATA]\n\n## Arquivos Entregues\n- [ ] [CLIENTE]_[EMPREND]_FILME_1920x1080_v[X]_[DATA].mp4\n- [ ] [CLIENTE]_[EMPREND]_FILME_3840x2160_v[X]_[DATA].mp4 (se 4K contratado)\n- [ ] [CLIENTE]_[EMPREND]_REELS_1080x1920_v[X]_[DATA].mp4\n- [ ] [CLIENTE]_[EMPREND]_FEED_1080x1080_v[X]_[DATA].mp4\n- [ ] [CLIENTE]_[EMPREND]_LEGENDADO_v[X]_[DATA].mp4 (se contratado)\n\n## Controle de Qualidade\n- [ ] Cor aprovada pelo Diretor Criativo em: _______\n- [ ] Áudio normalizado: -14 LUFS (web) | -23 LUFS (broadcast)\n- [ ] Sync verificado em todas as cenas: Sim / Não\n- [ ] Duração: ___:___ (dentro do briefing: ___:___)\n\n## Arquivamento\n- [ ] Master ProRes arquivado em: _____________\n- [ ] Backup nuvem confirmado: [LINK]\n- [ ] Projeto fechado no TBO OS: [LINK]\n\n## Assinaturas de Aprovação\n- Diretor Criativo: _________________ Data: _______\n- Atendimento: _________________ Data: _______\n- Cliente (aceite via email/link): ___ Data: _______\n```', 'tip', 9
FROM knowledge_sops WHERE slug = 'tbo-av-009-pos-producao-edicao-color-finalizacao';