-- Steps para SOP 3
DELETE FROM knowledge_sop_steps WHERE sop_id = (SELECT id FROM knowledge_sops WHERE slug = 'tbo-com-009-precificacao-projetos-por-bu');
INSERT INTO knowledge_sop_steps (sop_id, title, content, step_type, order_index)
SELECT id, 'Objetivo', E'Estabelecer o método padrão da TBO para precificar projetos em cada BU, garantindo margem de contribuição adequada, cobertura de custos diretos e indiretos, e competitividade de mercado. Eliminar precificações por feeling e criar consistência comercial em toda a empresa.', 'step', 0
FROM knowledge_sops WHERE slug = 'tbo-com-009-precificacao-projetos-por-bu'
UNION ALL
SELECT id, 'Escopo', E'Aplica-se a todos os projetos de todas as BUs. Executado pelo Diretor Comercial (Ruy) com suporte do Financeiro e dos Líderes de BU. Toda proposta comercial acima de R$5.000 deve passar por este processo antes do envio ao cliente.', 'step', 1
FROM knowledge_sops WHERE slug = 'tbo-com-009-precificacao-projetos-por-bu'
UNION ALL
SELECT id, 'RACI', E'| Atividade | Responsável | Aprovador | Consultado | Informado |\n|-----------|-------------|-----------|------------|-----------|\n| Levantamento de horas/custos | Líder de BU | Dir. Comercial | Time da BU | — |\n| Composição do preço | Dir. Comercial | Founder | Financeiro | — |\n| Validação de margem | Financeiro | Founder | Dir. Comercial | — |\n| Aprovação final | Founder | — | Dir. Comercial | Atendimento |\n| Desconto >10% | Founder | — | Dir. Comercial | Financeiro |', 'step', 2
FROM knowledge_sops WHERE slug = 'tbo-com-009-precificacao-projetos-por-bu'
UNION ALL
SELECT id, 'Pré-requisitos', E'- Briefing validado com escopo claro e lista de entregas definida\n- Tabela de custos operacionais da BU atualizada (salários, softwares, infraestrutura)\n- Tabela de preços de referência TBO (atualizada trimestralmente)\n- Histórico de projetos similares para benchmark interno (TBO OS → Relatórios → Lucratividade)\n- Acesso ao Simulador de Precificação no TBO OS → Financeiro', 'step', 3
FROM knowledge_sops WHERE slug = 'tbo-com-009-precificacao-projetos-por-bu'
UNION ALL
SELECT id, 'Procedimento', E'**Etapa 1 — Levantamento de Custos Diretos**\n1. Líder de BU estima horas por função (Sênior, Pleno, Júnior) para cada entrega\n2. Adicionar 15-20% de horas de gestão e 10% de QA/revisão\n3. Calcular custo de horas usando tabela interna (confidencial, TBO OS → Financeiro)\n4. Adicionar custos variáveis: freelancers, licenças, produção física, farm de render\n\n**Etapa 2 — Composição do Preço de Venda**\nFórmula: Preço = (Custo Direto × Markup BU) + Overhead + Margem\n- Markup por BU: D3D 2.5–3.5x | Branding 3.0–4.0x | AV 3.0–4.5x | Marketing 2.5–3.5x | Gamificação 3.5–5.0x\n- Overhead: 25-35% sobre custo direto\n- Margem líquida mínima: 25% (<R$10k), 30% (R$10–50k), 35% (>R$50k)\n\n**Etapa 3 — Validação de Margem**\n1. Financeiro revisa no simulador do TBO OS\n2. Valida: margem bruta ≥60%, margem líquida ≥ patamar, freelancers ≤30% do custo\n\n**Etapa 4 — Estratégia: 3 Opções**\n- Básico: escopo mínimo\n- Recomendado: escopo completo (oferta principal)\n- Premium: escopo expandido com serviços adicionais\n- Desconto máximo sem Founder: 10%\n\n**Etapa 5 — Formalização na Proposta**\n1. Inserir preços no template de proposta (SOP tbo-com-002)\n2. Descrever o que está incluído E o que NÃO está incluído\n3. Especificar rodadas de revisão, prazo e condições de pagamento\n4. Registrar no CRM (TBO OS → Comercial → Pipeline)', 'step', 4
FROM knowledge_sops WHERE slug = 'tbo-com-009-precificacao-projetos-por-bu'
UNION ALL
SELECT id, 'Checklist de Validação', E'- [ ] Horas estimadas por função revisadas pelo Líder de BU\n- [ ] Custos variáveis (freelancers, softwares, produção) incluídos\n- [ ] Markup dentro do range definido para a BU\n- [ ] Overhead de 25-35% aplicado\n- [ ] Margem líquida validada pelo Financeiro\n- [ ] 3 opções de escopo preparadas (Básico, Recomendado, Premium)\n- [ ] Escopo descrito com clareza — incluídos E não incluídos\n- [ ] Número de rodadas de revisão especificado\n- [ ] Proposta registrada no CRM antes do envio ao cliente', 'checkpoint', 5
FROM knowledge_sops WHERE slug = 'tbo-com-009-precificacao-projetos-por-bu'
UNION ALL
SELECT id, 'Ferramentas e Recursos', E'- **Simulador de margem**: TBO OS → Financeiro → Simulador de Proposta\n- **Tabela de custos internos**: TBO OS → Financeiro → Tabela de Custos (acesso restrito: founder + diretoria)\n- **Histórico de lucratividade**: TBO OS → Relatórios → Lucratividade por Projeto\n- **Template de proposta**: SOP tbo-com-002\n- **CRM/Pipeline**: TBO OS → Comercial', 'tip', 6
FROM knowledge_sops WHERE slug = 'tbo-com-009-precificacao-projetos-por-bu'
UNION ALL
SELECT id, 'SLAs e Métricas', E'| Métrica | Meta |\n|---------|------|\n| Tempo briefing → proposta | ≤ 3 dias úteis |\n| Margem bruta média TBO | ≥ 65% |\n| Margem líquida média | ≥ 30% |\n| Taxa de conversão proposta → contrato | ≥ 35% |\n| Propostas sem aditivo por sub-precificação | ≥ 80% |\n| Desconto médio concedido | ≤ 7% |', 'note', 7
FROM knowledge_sops WHERE slug = 'tbo-com-009-precificacao-projetos-por-bu'
UNION ALL
SELECT id, 'Troubleshooting', E'**Líder de BU subestima horas (sub-precificação recorrente)**\n→ Cruzar com histórico de projetos similares. Adicionar buffer de 20% em projetos com escopo incerto.\n\n**Cliente exige desconto além do autorizado**\n→ Acionar Founder para decisão estratégica. Avaliar: estratégico para portfólio ou declinar com elegância.\n\n**Concorrente apresentou preço 40% menor**\n→ Não entrar em leilão de preço. Reforçar diferenciação de qualidade. Documentar no CRM.\n\n**Escopo muito vago — difícil precificar**\n→ Solicitar briefing mais detalhado antes de precificar. Alternativa: proposta por hora (time & material) com estimativa de range.', 'warning', 8
FROM knowledge_sops WHERE slug = 'tbo-com-009-precificacao-projetos-por-bu'
UNION ALL
SELECT id, 'Template Anexo — Simulador de Precificação', E'```markdown\n# Simulador de Precificação — [CLIENTE] / [PROJETO]\nData: _______ | BU: _______ | Responsável: _______\n\n## Custo Direto\n| Função | Horas | Custo/h | Subtotal |\n|--------|-------|---------|----------|\n| Líder/Sênior | ___ | R$___ | R$___ |\n| Pleno | ___ | R$___ | R$___ |\n| Júnior | ___ | R$___ | R$___ |\n| Freelancer | ___ | R$___ | R$___ |\n| **Subtotal Horas** | | | **R$___** |\n\n## Custos Variáveis\n| Item | Valor |\n|------|-------|\n| Softwares/licenças | R$___ |\n| Farm de render | R$___ |\n| Outros | R$___ |\n| **Subtotal** | **R$___** |\n\n## Composição\n| Item | Valor |\n|------|-------|\n| Custo Direto Total | R$___ |\n| Overhead (___%) | R$___ |\n| Custo Total | R$___ |\n| Markup (___x) | — |\n| **Preço de Venda** | **R$___** |\n| Margem Bruta | ___% |\n| Margem Líquida | ___% |\n\n## Aprovação\n- Financeiro: _______ Data: _______\n- Founder (desconto >10%): _______ N/A\n```', 'tip', 9
FROM knowledge_sops WHERE slug = 'tbo-com-009-precificacao-projetos-por-bu';