import React from "react";
import {
  IconActivity,
  IconArrowDownCircle,
  IconArrowUpCircle,
  IconAward,
  IconBrandInstagram,
  IconChartBar,
  IconBell,
  IconBook,
  IconBriefcase,
  IconBuilding,
  IconBuildingSkyscraper,
  IconCalendar,
  IconCircleCheck,
  IconSquareCheck,
  IconClock,
  IconColumns3,
  IconAddressBook,
  IconCopy,
  IconCurrencyDollar,
  IconFileText,
  IconFileAlert,
  IconLayoutKanban,
  IconFolderOpen,
  IconTimeline,
  IconGift,
  IconGlobe,
  IconUsersGroup,
  IconHistory,
  IconLayoutDashboard,
  IconBulb,
  IconList,
  IconListCheck,
  IconLock,
  IconLogout,
  IconMail,
  IconMessage,
  IconPencil,
  IconChartPie,
  IconPlug,
  IconPresentation,
  IconRepeat,
  IconSettings,
  IconShare,
  IconShield,
  IconSpeakerphone,
  IconTarget,
  IconTrendingUp,
  IconUpload,
  IconUser,
  IconUserPlus,
  IconUsers,
  IconSchool,
  IconWallet,
  IconArrowsLeftRight,
  IconReceipt,
} from "@tabler/icons-react";

/**
 * Centralized icon registry — maps kebab-case keys to Tabler icon components.
 * Single source of truth for all sidebar and nav icons.
 */
const ICON_MAP: Record<string, React.ElementType> = {
  activity: IconActivity,
  "arrow-down-circle": IconArrowDownCircle,
  "arrow-up-circle": IconArrowUpCircle,
  award: IconAward,
  "bar-chart-3": IconChartBar,
  bell: IconBell,
  "brand-instagram": IconBrandInstagram,
  "chart-bar": IconChartBar,
  "book-open": IconBook,
  briefcase: IconBriefcase,
  building: IconBuilding,
  "building-2": IconBuildingSkyscraper,
  calendar: IconCalendar,
  "check-circle": IconCircleCheck,
  "check-square": IconSquareCheck,
  clock: IconClock,
  "columns-3": IconColumns3,
  contact: IconAddressBook,
  copy: IconCopy,
  "dollar-sign": IconCurrencyDollar,
  "file-text": IconFileText,
  "file-warning": IconFileAlert,
  "folder-kanban": IconLayoutKanban,
  "folder-open": IconFolderOpen,
  "gantt-chart-square": IconTimeline,
  gift: IconGift,
  globe: IconGlobe,
  "heart-handshake": IconUsersGroup,
  history: IconHistory,
  kanban: IconLayoutKanban,
  "layout-dashboard": IconLayoutDashboard,
  lightbulb: IconBulb,
  list: IconList,
  "list-checks": IconListCheck,
  lock: IconLock,
  "log-out": IconLogout,
  mail: IconMail,
  "message-square": IconMessage,
  pencil: IconPencil,
  "pen-tool": IconPencil,
  "pie-chart": IconChartPie,
  plug: IconPlug,
  presentation: IconPresentation,
  repeat: IconRepeat,
  settings: IconSettings,
  "share-2": IconShare,
  shield: IconShield,
  speakerphone: IconSpeakerphone,
  target: IconTarget,
  "trending-up": IconTrendingUp,
  upload: IconUpload,
  user: IconUser,
  "user-plus": IconUserPlus,
  school: IconSchool,
  users: IconUsers,
  "users-group": IconUsersGroup,
  wallet: IconWallet,
  "git-compare": IconArrowsLeftRight,
  receipt: IconReceipt,
};

/** Get a Tabler icon by kebab-case key. Falls back to IconLayoutDashboard. */
export function getIcon(name: string): React.ElementType {
  return ICON_MAP[name] ?? IconLayoutDashboard;
}

export { ICON_MAP };
