import {
  Activity,
  ArrowDownCircle,
  ArrowUpCircle,
  Award,
  BarChart3,
  Bell,
  BookOpen,
  Briefcase,
  Building,
  Building2,
  Calendar,
  CheckCircle,
  CheckSquare,
  Clock,
  Columns3,
  Contact,
  Copy,
  DollarSign,
  FileText,
  FileWarning,
  FolderKanban,
  FolderOpen,
  GanttChartSquare,
  Gift,
  Globe,
  HeartHandshake,
  History,
  Kanban,
  LayoutDashboard,
  Lightbulb,
  List,
  ListChecks,
  Lock,
  LogOut,
  MessageSquare,
  PenTool,
  PieChart,
  Plug,
  Presentation,
  Repeat,
  Settings,
  Share2,
  Shield,
  Target,
  TrendingUp,
  Upload,
  User,
  UserPlus,
  Users,
  Wallet,
  type LucideIcon,
} from "lucide-react";

/**
 * Centralized icon registry — maps kebab-case keys to Lucide components.
 * Single source of truth for all sidebar and nav icons.
 */
const ICON_MAP: Record<string, LucideIcon> = {
  activity: Activity,
  "arrow-down-circle": ArrowDownCircle,
  "arrow-up-circle": ArrowUpCircle,
  award: Award,
  "bar-chart-3": BarChart3,
  bell: Bell,
  "book-open": BookOpen,
  briefcase: Briefcase,
  building: Building,
  "building-2": Building2,
  calendar: Calendar,
  "check-circle": CheckCircle,
  "check-square": CheckSquare,
  clock: Clock,
  "columns-3": Columns3,
  contact: Contact,
  copy: Copy,
  "dollar-sign": DollarSign,
  "file-text": FileText,
  "file-warning": FileWarning,
  "folder-kanban": FolderKanban,
  "folder-open": FolderOpen,
  "gantt-chart-square": GanttChartSquare,
  gift: Gift,
  globe: Globe,
  "heart-handshake": HeartHandshake,
  history: History,
  kanban: Kanban,
  "layout-dashboard": LayoutDashboard,
  lightbulb: Lightbulb,
  list: List,
  "list-checks": ListChecks,
  lock: Lock,
  "log-out": LogOut,
  "message-square": MessageSquare,
  "pen-tool": PenTool,
  "pie-chart": PieChart,
  plug: Plug,
  presentation: Presentation,
  repeat: Repeat,
  settings: Settings,
  "share-2": Share2,
  shield: Shield,
  target: Target,
  "trending-up": TrendingUp,
  upload: Upload,
  user: User,
  "user-plus": UserPlus,
  users: Users,
  wallet: Wallet,
};

/** Get a Lucide icon by kebab-case key. Falls back to LayoutDashboard. */
export function getIcon(name: string): LucideIcon {
  return ICON_MAP[name] ?? LayoutDashboard;
}

export { ICON_MAP };
