// Dados ilustrativos de lancamentos imobiliarios no Parana (foco RMC)
// Sera substituido por integracao com API Orulo

export interface Lancamento {
  id: string;
  nome: string;
  incorporadora: string;
  bairro: string;
  cidade: string;
  regional?: string;
  tipologia: "Studio" | "1 Dorm" | "2 Dorms" | "3 Dorms" | "4+ Dorms" | "Comercial";
  unidades: number;
  unidadesVendidas: number;
  precoMin: number;
  precoMax: number;
  precoM2: number;
  metragemMin: number;
  metragemMax: number;
  dataLancamento: string;
  previsaoEntrega: string;
  status: "pre-lancamento" | "lancamento" | "em-obras" | "pronto";
  destaque?: boolean;
}

export const LANCAMENTOS: Lancamento[] = [
  {
    id: "lanc-001",
    nome: "Scenarium Batel",
    incorporadora: "Laguna",
    bairro: "Batel",
    cidade: "Curitiba",
    regional: "Matriz",
    tipologia: "4+ Dorms",
    unidades: 32,
    unidadesVendidas: 28,
    precoMin: 3_200_000,
    precoMax: 5_800_000,
    precoM2: 18_500,
    metragemMin: 170,
    metragemMax: 310,
    dataLancamento: "2024-03-15",
    previsaoEntrega: "2027-06-01",
    status: "em-obras",
    destaque: true,
  },
  {
    id: "lanc-002",
    nome: "HUB Compact Living",
    incorporadora: "GT Building",
    bairro: "Centro",
    cidade: "Curitiba",
    regional: "Matriz",
    tipologia: "Studio",
    unidades: 180,
    unidadesVendidas: 162,
    precoMin: 310_000,
    precoMax: 420_000,
    precoM2: 12_800,
    metragemMin: 24,
    metragemMax: 33,
    dataLancamento: "2024-01-20",
    previsaoEntrega: "2026-08-01",
    status: "em-obras",
  },
  {
    id: "lanc-003",
    nome: "Verace Champagnat",
    incorporadora: "Plaenge",
    bairro: "Champagnat",
    cidade: "Curitiba",
    regional: "Matriz",
    tipologia: "3 Dorms",
    unidades: 48,
    unidadesVendidas: 41,
    precoMin: 1_280_000,
    precoMax: 1_950_000,
    precoM2: 14_200,
    metragemMin: 90,
    metragemMax: 137,
    dataLancamento: "2024-05-10",
    previsaoEntrega: "2027-09-01",
    status: "em-obras",
  },
  {
    id: "lanc-004",
    nome: "YOLO Cabral",
    incorporadora: "GT Building",
    bairro: "Cabral",
    cidade: "Curitiba",
    regional: "Boa Vista",
    tipologia: "1 Dorm",
    unidades: 120,
    unidadesVendidas: 54,
    precoMin: 385_000,
    precoMax: 520_000,
    precoM2: 11_900,
    metragemMin: 32,
    metragemMax: 44,
    dataLancamento: "2025-01-18",
    previsaoEntrega: "2028-03-01",
    status: "lancamento",
    destaque: true,
  },
  {
    id: "lanc-005",
    nome: "Reserva Ecoville",
    incorporadora: "Tha",
    bairro: "Ecoville",
    cidade: "Curitiba",
    regional: "Santa Felicidade",
    tipologia: "3 Dorms",
    unidades: 64,
    unidadesVendidas: 19,
    precoMin: 980_000,
    precoMax: 1_450_000,
    precoM2: 12_600,
    metragemMin: 78,
    metragemMax: 115,
    dataLancamento: "2025-02-05",
    previsaoEntrega: "2028-06-01",
    status: "lancamento",
  },
  {
    id: "lanc-006",
    nome: "Villagio Agua Verde",
    incorporadora: "A.Yoshii",
    bairro: "Agua Verde",
    cidade: "Curitiba",
    regional: "Portao",
    tipologia: "2 Dorms",
    unidades: 96,
    unidadesVendidas: 88,
    precoMin: 620_000,
    precoMax: 850_000,
    precoM2: 10_800,
    metragemMin: 57,
    metragemMax: 79,
    dataLancamento: "2023-09-12",
    previsaoEntrega: "2026-12-01",
    status: "em-obras",
  },
  {
    id: "lanc-007",
    nome: "Sky Tower Juveve",
    incorporadora: "Vanguard",
    bairro: "Juveve",
    cidade: "Curitiba",
    regional: "Matriz",
    tipologia: "4+ Dorms",
    unidades: 24,
    unidadesVendidas: 24,
    precoMin: 2_800_000,
    precoMax: 4_200_000,
    precoM2: 16_900,
    metragemMin: 165,
    metragemMax: 248,
    dataLancamento: "2023-06-01",
    previsaoEntrega: "2026-03-01",
    status: "pronto",
  },
  {
    id: "lanc-008",
    nome: "Vida Nova Campo Comprido",
    incorporadora: "MRV",
    bairro: "Campo Comprido",
    cidade: "Curitiba",
    regional: "Santa Felicidade",
    tipologia: "2 Dorms",
    unidades: 240,
    unidadesVendidas: 210,
    precoMin: 295_000,
    precoMax: 380_000,
    precoM2: 6_200,
    metragemMin: 47,
    metragemMax: 61,
    dataLancamento: "2023-11-20",
    previsaoEntrega: "2026-05-01",
    status: "em-obras",
  },
  {
    id: "lanc-009",
    nome: "Palazzo Bigorrilho",
    incorporadora: "Laguna",
    bairro: "Bigorrilho",
    cidade: "Curitiba",
    regional: "Matriz",
    tipologia: "3 Dorms",
    unidades: 36,
    unidadesVendidas: 33,
    precoMin: 1_550_000,
    precoMax: 2_300_000,
    precoM2: 15_800,
    metragemMin: 98,
    metragemMax: 145,
    dataLancamento: "2024-02-28",
    previsaoEntrega: "2027-04-01",
    status: "em-obras",
  },
  {
    id: "lanc-010",
    nome: "Terrasse Alto da XV",
    incorporadora: "Terrasse",
    bairro: "Alto da XV",
    cidade: "Curitiba",
    regional: "Boa Vista",
    tipologia: "2 Dorms",
    unidades: 72,
    unidadesVendidas: 30,
    precoMin: 580_000,
    precoMax: 780_000,
    precoM2: 10_200,
    metragemMin: 57,
    metragemMax: 76,
    dataLancamento: "2025-03-01",
    previsaoEntrega: "2028-09-01",
    status: "lancamento",
  },
  {
    id: "lanc-011",
    nome: "Open Mall Batel",
    incorporadora: "GT Building",
    bairro: "Batel",
    cidade: "Curitiba",
    regional: "Matriz",
    tipologia: "Comercial",
    unidades: 58,
    unidadesVendidas: 22,
    precoMin: 450_000,
    precoMax: 1_200_000,
    precoM2: 19_500,
    metragemMin: 23,
    metragemMax: 62,
    dataLancamento: "2025-04-10",
    previsaoEntrega: "2028-12-01",
    status: "pre-lancamento",
    destaque: true,
  },
  {
    id: "lanc-012",
    nome: "Pineville Garden",
    incorporadora: "Pineville",
    bairro: "Santa Felicidade",
    cidade: "Curitiba",
    regional: "Santa Felicidade",
    tipologia: "3 Dorms",
    unidades: 80,
    unidadesVendidas: 44,
    precoMin: 850_000,
    precoMax: 1_180_000,
    precoM2: 11_400,
    metragemMin: 75,
    metragemMax: 104,
    dataLancamento: "2024-08-15",
    previsaoEntrega: "2027-12-01",
    status: "em-obras",
  },
  {
    id: "lanc-013",
    nome: "NEO Studios Reboucas",
    incorporadora: "Vanguard",
    bairro: "Reboucas",
    cidade: "Curitiba",
    regional: "Matriz",
    tipologia: "Studio",
    unidades: 200,
    unidadesVendidas: 140,
    precoMin: 280_000,
    precoMax: 395_000,
    precoM2: 13_100,
    metragemMin: 21,
    metragemMax: 30,
    dataLancamento: "2024-06-20",
    previsaoEntrega: "2027-08-01",
    status: "em-obras",
  },
  {
    id: "lanc-014",
    nome: "Gran Parc Cabral",
    incorporadora: "Plaenge",
    bairro: "Cabral",
    cidade: "Curitiba",
    regional: "Boa Vista",
    tipologia: "4+ Dorms",
    unidades: 40,
    unidadesVendidas: 12,
    precoMin: 2_500_000,
    precoMax: 3_800_000,
    precoM2: 17_200,
    metragemMin: 145,
    metragemMax: 220,
    dataLancamento: "2025-05-01",
    previsaoEntrega: "2029-03-01",
    status: "pre-lancamento",
  },
  {
    id: "lanc-015",
    nome: "Vista Parque Barigui",
    incorporadora: "Tha",
    bairro: "Santo Inacio",
    cidade: "Curitiba",
    regional: "Santa Felicidade",
    tipologia: "2 Dorms",
    unidades: 108,
    unidadesVendidas: 65,
    precoMin: 540_000,
    precoMax: 720_000,
    precoM2: 9_800,
    metragemMin: 55,
    metragemMax: 73,
    dataLancamento: "2024-10-01",
    previsaoEntrega: "2027-10-01",
    status: "em-obras",
  },
  {
    id: "lanc-016",
    nome: "Residencial Londrina Park",
    incorporadora: "A.Yoshii",
    bairro: "Gleba Palhano",
    cidade: "Londrina",
    tipologia: "3 Dorms",
    unidades: 56,
    unidadesVendidas: 48,
    precoMin: 750_000,
    precoMax: 1_100_000,
    precoM2: 9_200,
    metragemMin: 82,
    metragemMax: 120,
    dataLancamento: "2024-04-10",
    previsaoEntrega: "2027-02-01",
    status: "em-obras",
  },
  {
    id: "lanc-017",
    nome: "Maringa Towers",
    incorporadora: "Plaenge",
    bairro: "Zona 07",
    cidade: "Maringa",
    tipologia: "2 Dorms",
    unidades: 88,
    unidadesVendidas: 72,
    precoMin: 480_000,
    precoMax: 680_000,
    precoM2: 8_500,
    metragemMin: 56,
    metragemMax: 80,
    dataLancamento: "2024-07-01",
    previsaoEntrega: "2027-07-01",
    status: "em-obras",
  },
  {
    id: "lanc-018",
    nome: "SoHo Hugo Lange",
    incorporadora: "GT Building",
    bairro: "Hugo Lange",
    cidade: "Curitiba",
    regional: "Matriz",
    tipologia: "1 Dorm",
    unidades: 144,
    unidadesVendidas: 98,
    precoMin: 410_000,
    precoMax: 560_000,
    precoM2: 12_400,
    metragemMin: 33,
    metragemMax: 45,
    dataLancamento: "2024-09-05",
    previsaoEntrega: "2027-11-01",
    status: "em-obras",
  },
  {
    id: "lanc-019",
    nome: "Praca das Flores",
    incorporadora: "MRV",
    bairro: "Pinheirinho",
    cidade: "Curitiba",
    regional: "Pinheirinho",
    tipologia: "2 Dorms",
    unidades: 320,
    unidadesVendidas: 288,
    precoMin: 260_000,
    precoMax: 345_000,
    precoM2: 5_800,
    metragemMin: 45,
    metragemMax: 59,
    dataLancamento: "2023-08-10",
    previsaoEntrega: "2026-02-01",
    status: "pronto",
  },
  {
    id: "lanc-020",
    nome: "Lumiere Ecoville",
    incorporadora: "Laguna",
    bairro: "Ecoville",
    cidade: "Curitiba",
    regional: "Santa Felicidade",
    tipologia: "4+ Dorms",
    unidades: 28,
    unidadesVendidas: 10,
    precoMin: 3_500_000,
    precoMax: 5_200_000,
    precoM2: 19_800,
    metragemMin: 177,
    metragemMax: 262,
    dataLancamento: "2025-06-01",
    previsaoEntrega: "2029-06-01",
    status: "pre-lancamento",
    destaque: true,
  },
  {
    id: "lanc-021",
    nome: "ON Centro Civico",
    incorporadora: "Vanguard",
    bairro: "Centro Civico",
    cidade: "Curitiba",
    regional: "Matriz",
    tipologia: "Studio",
    unidades: 160,
    unidadesVendidas: 48,
    precoMin: 295_000,
    precoMax: 410_000,
    precoM2: 13_500,
    metragemMin: 22,
    metragemMax: 30,
    dataLancamento: "2025-03-20",
    previsaoEntrega: "2028-07-01",
    status: "lancamento",
  },
  {
    id: "lanc-022",
    nome: "Jardins Cascavel",
    incorporadora: "Tha",
    bairro: "Centro",
    cidade: "Cascavel",
    tipologia: "2 Dorms",
    unidades: 72,
    unidadesVendidas: 58,
    precoMin: 380_000,
    precoMax: 520_000,
    precoM2: 7_100,
    metragemMin: 54,
    metragemMax: 73,
    dataLancamento: "2024-02-15",
    previsaoEntrega: "2026-11-01",
    status: "em-obras",
  },
  {
    id: "lanc-023",
    nome: "Vivant Merces",
    incorporadora: "Terrasse",
    bairro: "Merces",
    cidade: "Curitiba",
    regional: "Matriz",
    tipologia: "1 Dorm",
    unidades: 96,
    unidadesVendidas: 38,
    precoMin: 365_000,
    precoMax: 490_000,
    precoM2: 11_200,
    metragemMin: 33,
    metragemMax: 44,
    dataLancamento: "2025-02-20",
    previsaoEntrega: "2028-05-01",
    status: "lancamento",
  },
  {
    id: "lanc-024",
    nome: "Opus SJP",
    incorporadora: "Pineville",
    bairro: "Centro",
    cidade: "Sao Jose dos Pinhais",
    tipologia: "2 Dorms",
    unidades: 144,
    unidadesVendidas: 120,
    precoMin: 340_000,
    precoMax: 460_000,
    precoM2: 6_800,
    metragemMin: 50,
    metragemMax: 68,
    dataLancamento: "2024-03-01",
    previsaoEntrega: "2026-09-01",
    status: "em-obras",
  },
  {
    id: "lanc-025",
    nome: "Alto Prado Seminario",
    incorporadora: "A.Yoshii",
    bairro: "Seminario",
    cidade: "Curitiba",
    regional: "Portao",
    tipologia: "3 Dorms",
    unidades: 52,
    unidadesVendidas: 35,
    precoMin: 920_000,
    precoMax: 1_350_000,
    precoM2: 11_800,
    metragemMin: 78,
    metragemMax: 114,
    dataLancamento: "2024-11-10",
    previsaoEntrega: "2028-02-01",
    status: "em-obras",
  },
];

// ── Constantes derivadas ────────────────────────────────────────

export const INCORPORADORAS = [
  ...new Set(LANCAMENTOS.map((l) => l.incorporadora)),
].sort();

export const TIPOLOGIAS: Lancamento["tipologia"][] = [
  "Studio",
  "1 Dorm",
  "2 Dorms",
  "3 Dorms",
  "4+ Dorms",
  "Comercial",
];

export const STATUS_LABELS: Record<Lancamento["status"], string> = {
  "pre-lancamento": "Pre-lancamento",
  lancamento: "Lancamento",
  "em-obras": "Em obras",
  pronto: "Pronto",
};

export const CIDADES = [
  ...new Set(LANCAMENTOS.map((l) => l.cidade)),
].sort();
